---
title: "Tournament Analysis"
author: "Zoe Pratt"
date: "4/6/2022"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(ggthemes)
library(car)
library(rstatix)
library(equivalence)
library(knitr)
```

```{r}
player_data = read.csv('/Users/zoepratt/Documents/GitHub/Style-Transfer-GAN/player_piece_sac_data.csv')
tour_data = read.csv('/Users/zoepratt/Documents/GitHub/Style-Transfer-GAN/models_game_data.csv')

```

```{r}
ggplot(tour_data, aes(x = num_moves))+
  geom_histogram(fill = 'lightgreen', color = 'darkgreen') +
  labs(x = 'Number of Moves in Chess Match', y = 'Count', title = 'Distribution of Number of Moves in a Chess Match') +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
ggplot(tour_data, aes(x = total_sac))+
  geom_histogram(fill = 'lightblue', color = 'blue') +
  labs(x = 'Number of Moves in Chess Match', y = 'Count', title = 'Distribution of Number of Moves in a Chess Match') +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
kruskal.test(black_sac ~ Black, data = tour_data)
```

